version: '3.1'

services:
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_USERNAME=usedeall
      - MONGODB_PASSWORD=secret
      - MONGODB_DATABASE=usedeall_db
      - MONGODB_ROOT_PASSWORD=usedeall_root
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - mongodb_data:/bitnami/mongodb

  usedeall-app:
    image: rafidianto/usedeall-test
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3001:3000
    environment:
      - LOG_LEVEL=debug
      - DB_USER=usedeall
      - DB_PASS=secret
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=usedeall_db
      - DB_REPLICA_SET=rs1
      - ACCESS_TOKEN_SECRET=123
      - REFRESH_TOKEN_SECRET=123

volumes:
  mongodb_data:
